name: Snyk Container

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 */2 * * *'

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build a Docker image
      run: docker build -t your/image-to-test .
 
    - name: Run Snyk to check Docker image for vulnerabilities
      id: check-fail
      continue-on-error: false
      uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
      env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: your/image-to-test
        args: |
          --file=Dockerfile
          --severity-threshold=high
          --sarif-file-output=snyk-container.sarif
    
 
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-container.sarif
